"""ISO-3166 alpha-2 country names, for labelling the region folders.

Written out rather than pulled from a package: the pipeline runs in CI where
every dependency is a failure mode, and this list does not change often.

The flag emoji is derived from the code (regional indicator symbols) rather
than stored, so there is one place for a country to be wrong instead of two.
"uk" is included alongside "gb" because iptv-org tvg-ids use it.
"""

from __future__ import annotations

COUNTRY_NAMES: dict[str, str] = {
    'ad': 'Andorra',
    'ae': 'United Arab Emirates',
    'af': 'Afghanistan',
    'ag': 'Antigua and Barbuda',
    'ai': 'Anguilla',
    'al': 'Albania',
    'am': 'Armenia',
    'ao': 'Angola',
    'aq': 'Antarctica',
    'ar': 'Argentina',
    'as': 'American Samoa',
    'at': 'Austria',
    'au': 'Australia',
    'aw': 'Aruba',
    'ax': 'Åland Islands',
    'az': 'Azerbaijan',
    'ba': 'Bosnia and Herzegovina',
    'bb': 'Barbados',
    'bd': 'Bangladesh',
    'be': 'Belgium',
    'bf': 'Burkina Faso',
    'bg': 'Bulgaria',
    'bh': 'Bahrain',
    'bi': 'Burundi',
    'bj': 'Benin',
    'bl': 'Saint Barthélemy',
    'bm': 'Bermuda',
    'bn': 'Brunei',
    'bo': 'Bolivia',
    'bq': 'Caribbean Netherlands',
    'br': 'Brazil',
    'bs': 'Bahamas',
    'bt': 'Bhutan',
    'bw': 'Botswana',
    'by': 'Belarus',
    'bz': 'Belize',
    'ca': 'Canada',
    'cc': 'Cocos Islands',
    'cd': 'DR Congo',
    'cf': 'Central African Republic',
    'cg': 'Congo',
    'ch': 'Switzerland',
    'ci': "Côte d'Ivoire",
    'ck': 'Cook Islands',
    'cl': 'Chile',
    'cm': 'Cameroon',
    'cn': 'China',
    'co': 'Colombia',
    'cr': 'Costa Rica',
    'cu': 'Cuba',
    'cv': 'Cape Verde',
    'cw': 'Curaçao',
    'cx': 'Christmas Island',
    'cy': 'Cyprus',
    'cz': 'Czechia',
    'de': 'Germany',
    'dj': 'Djibouti',
    'dk': 'Denmark',
    'dm': 'Dominica',
    'do': 'Dominican Republic',
    'dz': 'Algeria',
    'ec': 'Ecuador',
    'ee': 'Estonia',
    'eg': 'Egypt',
    'eh': 'Western Sahara',
    'er': 'Eritrea',
    'es': 'Spain',
    'et': 'Ethiopia',
    'fi': 'Finland',
    'fj': 'Fiji',
    'fk': 'Falkland Islands',
    'fm': 'Micronesia',
    'fo': 'Faroe Islands',
    'fr': 'France',
    'ga': 'Gabon',
    'gb': 'United Kingdom',
    'gd': 'Grenada',
    'ge': 'Georgia',
    'gf': 'French Guiana',
    'gg': 'Guernsey',
    'gh': 'Ghana',
    'gi': 'Gibraltar',
    'gl': 'Greenland',
    'gm': 'Gambia',
    'gn': 'Guinea',
    'gp': 'Guadeloupe',
    'gq': 'Equatorial Guinea',
    'gr': 'Greece',
    'gt': 'Guatemala',
    'gu': 'Guam',
    'gw': 'Guinea-Bissau',
    'gy': 'Guyana',
    'hk': 'Hong Kong',
    'hn': 'Honduras',
    'hr': 'Croatia',
    'ht': 'Haiti',
    'hu': 'Hungary',
    'id': 'Indonesia',
    'ie': 'Ireland',
    'il': 'Israel',
    'im': 'Isle of Man',
    'in': 'India',
    'io': 'British Indian Ocean Territory',
    'iq': 'Iraq',
    'ir': 'Iran',
    'is': 'Iceland',
    'it': 'Italy',
    'je': 'Jersey',
    'jm': 'Jamaica',
    'jo': 'Jordan',
    'jp': 'Japan',
    'ke': 'Kenya',
    'kg': 'Kyrgyzstan',
    'kh': 'Cambodia',
    'ki': 'Kiribati',
    'km': 'Comoros',
    'kn': 'Saint Kitts and Nevis',
    'kp': 'North Korea',
    'kr': 'South Korea',
    'kw': 'Kuwait',
    'ky': 'Cayman Islands',
    'kz': 'Kazakhstan',
    'la': 'Laos',
    'lb': 'Lebanon',
    'lc': 'Saint Lucia',
    'li': 'Liechtenstein',
    'lk': 'Sri Lanka',
    'lr': 'Liberia',
    'ls': 'Lesotho',
    'lt': 'Lithuania',
    'lu': 'Luxembourg',
    'lv': 'Latvia',
    'ly': 'Libya',
    'ma': 'Morocco',
    'mc': 'Monaco',
    'md': 'Moldova',
    'me': 'Montenegro',
    'mf': 'Saint Martin',
    'mg': 'Madagascar',
    'mh': 'Marshall Islands',
    'mk': 'North Macedonia',
    'ml': 'Mali',
    'mm': 'Myanmar',
    'mn': 'Mongolia',
    'mo': 'Macao',
    'mp': 'Northern Mariana Islands',
    'mq': 'Martinique',
    'mr': 'Mauritania',
    'ms': 'Montserrat',
    'mt': 'Malta',
    'mu': 'Mauritius',
    'mv': 'Maldives',
    'mw': 'Malawi',
    'mx': 'Mexico',
    'my': 'Malaysia',
    'mz': 'Mozambique',
    'na': 'Namibia',
    'nc': 'New Caledonia',
    'ne': 'Niger',
    'nf': 'Norfolk Island',
    'ng': 'Nigeria',
    'ni': 'Nicaragua',
    'nl': 'Netherlands',
    'no': 'Norway',
    'np': 'Nepal',
    'nr': 'Nauru',
    'nu': 'Niue',
    'nz': 'New Zealand',
    'om': 'Oman',
    'pa': 'Panama',
    'pe': 'Peru',
    'pf': 'French Polynesia',
    'pg': 'Papua New Guinea',
    'ph': 'Philippines',
    'pk': 'Pakistan',
    'pl': 'Poland',
    'pm': 'Saint Pierre and Miquelon',
    'pn': 'Pitcairn',
    'pr': 'Puerto Rico',
    'ps': 'Palestine',
    'pt': 'Portugal',
    'pw': 'Palau',
    'py': 'Paraguay',
    'qa': 'Qatar',
    're': 'Réunion',
    'ro': 'Romania',
    'rs': 'Serbia',
    'ru': 'Russia',
    'rw': 'Rwanda',
    'sa': 'Saudi Arabia',
    'sb': 'Solomon Islands',
    'sc': 'Seychelles',
    'sd': 'Sudan',
    'se': 'Sweden',
    'sg': 'Singapore',
    'sh': 'Saint Helena',
    'si': 'Slovenia',
    'sj': 'Svalbard and Jan Mayen',
    'sk': 'Slovakia',
    'sl': 'Sierra Leone',
    'sm': 'San Marino',
    'sn': 'Senegal',
    'so': 'Somalia',
    'sr': 'Suriname',
    'ss': 'South Sudan',
    'st': 'São Tomé and Príncipe',
    'sv': 'El Salvador',
    'sx': 'Sint Maarten',
    'sy': 'Syria',
    'sz': 'Eswatini',
    'tc': 'Turks and Caicos Islands',
    'td': 'Chad',
    'tf': 'French Southern Territories',
    'tg': 'Togo',
    'th': 'Thailand',
    'tj': 'Tajikistan',
    'tk': 'Tokelau',
    'tl': 'Timor-Leste',
    'tm': 'Turkmenistan',
    'tn': 'Tunisia',
    'to': 'Tonga',
    'tr': 'Türkiye',
    'tt': 'Trinidad and Tobago',
    'tv': 'Tuvalu',
    'tw': 'Taiwan',
    'tz': 'Tanzania',
    'ua': 'Ukraine',
    'ug': 'Uganda',
    'uk': 'United Kingdom',
    'um': 'U.S. Minor Outlying Islands',
    'us': 'United States',
    'uy': 'Uruguay',
    'uz': 'Uzbekistan',
    'va': 'Vatican City',
    'vc': 'Saint Vincent and the Grenadines',
    've': 'Venezuela',
    'vg': 'British Virgin Islands',
    'vi': 'U.S. Virgin Islands',
    'vn': 'Vietnam',
    'vu': 'Vanuatu',
    'wf': 'Wallis and Futuna',
    'ws': 'Samoa',
    'xk': 'Kosovo',
    'ye': 'Yemen',
    'yt': 'Mayotte',
    'za': 'South Africa',
    'zm': 'Zambia',
    'zw': 'Zimbabwe',
}


# Codes that are not themselves flag sequences, mapped to the one that is.
# "uk" is what iptv-org writes; the assigned regional-indicator pair is "gb",
# and U+1F1FA U+1F1F0 renders as two letter boxes on a TV rather than a flag.
_FLAG_ALIASES = {"uk": "gb"}


def flag_emoji(code: str) -> str:
    """Regional-indicator pair for a two-letter code, or "" if it is not one."""
    c = (code or "").strip().lower()
    c = _FLAG_ALIASES.get(c, c)
    if len(c) != 2 or not c.isalpha():
        return ""
    return "".join(chr(0x1F1E6 + ord(ch) - ord("a")) for ch in c)


def country_label(code: str) -> str:
    """"🇧🇩 Bangladesh" for a known code, "" when the code is not one we name."""
    c = (code or "").strip().lower()
    name = COUNTRY_NAMES.get(c)
    if not name:
        return ""
    flag = flag_emoji(c)
    return f"{flag} {name}" if flag else name


# Continent of each country, so 167 country folders can sit behind six screens
# instead of one list that no TV remote wants to scroll. Codes not listed here
# fall into "other".
_CONTINENT_OF: dict[str, str] = {
    'af': 'as',
    'am': 'as',
    'az': 'as',
    'bd': 'as',
    'bh': 'as',
    'bn': 'as',
    'bt': 'as',
    'cn': 'as',
    'cy': 'as',
    'ge': 'as',
    'hk': 'as',
    'id': 'as',
    'il': 'as',
    'in': 'as',
    'iq': 'as',
    'ir': 'as',
    'jo': 'as',
    'jp': 'as',
    'kg': 'as',
    'kh': 'as',
    'kp': 'as',
    'kr': 'as',
    'kw': 'as',
    'kz': 'as',
    'la': 'as',
    'lb': 'as',
    'lk': 'as',
    'mm': 'as',
    'mn': 'as',
    'mo': 'as',
    'mv': 'as',
    'my': 'as',
    'np': 'as',
    'om': 'as',
    'ph': 'as',
    'pk': 'as',
    'ps': 'as',
    'qa': 'as',
    'sa': 'as',
    'sg': 'as',
    'sy': 'as',
    'th': 'as',
    'tj': 'as',
    'tm': 'as',
    'tr': 'as',
    'tw': 'as',
    'uz': 'as',
    'vn': 'as',
    'ye': 'as',
    'ae': 'as',
    'ad': 'eu',
    'al': 'eu',
    'at': 'eu',
    'ax': 'eu',
    'ba': 'eu',
    'be': 'eu',
    'bg': 'eu',
    'by': 'eu',
    'ch': 'eu',
    'cz': 'eu',
    'de': 'eu',
    'dk': 'eu',
    'ee': 'eu',
    'es': 'eu',
    'fi': 'eu',
    'fo': 'eu',
    'fr': 'eu',
    'gb': 'eu',
    'gg': 'eu',
    'gi': 'eu',
    'gr': 'eu',
    'hr': 'eu',
    'hu': 'eu',
    'ie': 'eu',
    'im': 'eu',
    'is': 'eu',
    'it': 'eu',
    'je': 'eu',
    'li': 'eu',
    'lt': 'eu',
    'lu': 'eu',
    'lv': 'eu',
    'mc': 'eu',
    'md': 'eu',
    'me': 'eu',
    'mk': 'eu',
    'mt': 'eu',
    'nl': 'eu',
    'no': 'eu',
    'pl': 'eu',
    'pt': 'eu',
    'ro': 'eu',
    'rs': 'eu',
    'ru': 'eu',
    'se': 'eu',
    'si': 'eu',
    'sk': 'eu',
    'sm': 'eu',
    'ua': 'eu',
    'uk': 'eu',
    'va': 'eu',
    'xk': 'eu',
    'ao': 'af',
    'bf': 'af',
    'bi': 'af',
    'bj': 'af',
    'bw': 'af',
    'cd': 'af',
    'cf': 'af',
    'cg': 'af',
    'ci': 'af',
    'cm': 'af',
    'cv': 'af',
    'dj': 'af',
    'dz': 'af',
    'eg': 'af',
    'eh': 'af',
    'er': 'af',
    'et': 'af',
    'ga': 'af',
    'gh': 'af',
    'gm': 'af',
    'gn': 'af',
    'gq': 'af',
    'gw': 'af',
    'ke': 'af',
    'km': 'af',
    'lr': 'af',
    'ls': 'af',
    'ly': 'af',
    'ma': 'af',
    'mg': 'af',
    'ml': 'af',
    'mr': 'af',
    'mu': 'af',
    'mw': 'af',
    'mz': 'af',
    'na': 'af',
    'ne': 'af',
    'ng': 'af',
    're': 'af',
    'rw': 'af',
    'sc': 'af',
    'sd': 'af',
    'sh': 'af',
    'sl': 'af',
    'sn': 'af',
    'so': 'af',
    'ss': 'af',
    'st': 'af',
    'sz': 'af',
    'td': 'af',
    'tg': 'af',
    'tn': 'af',
    'tz': 'af',
    'ug': 'af',
    'yt': 'af',
    'za': 'af',
    'zm': 'af',
    'zw': 'af',
    'ag': 'na',
    'ai': 'na',
    'aw': 'na',
    'bb': 'na',
    'bl': 'na',
    'bm': 'na',
    'bq': 'na',
    'bs': 'na',
    'bz': 'na',
    'ca': 'na',
    'cr': 'na',
    'cu': 'na',
    'cw': 'na',
    'dm': 'na',
    'do': 'na',
    'gd': 'na',
    'gl': 'na',
    'gp': 'na',
    'gt': 'na',
    'hn': 'na',
    'ht': 'na',
    'jm': 'na',
    'kn': 'na',
    'ky': 'na',
    'lc': 'na',
    'mf': 'na',
    'mq': 'na',
    'ms': 'na',
    'mx': 'na',
    'ni': 'na',
    'pa': 'na',
    'pm': 'na',
    'pr': 'na',
    'sv': 'na',
    'sx': 'na',
    'tc': 'na',
    'tt': 'na',
    'us': 'na',
    'vc': 'na',
    'vg': 'na',
    'vi': 'na',
    'ar': 'sa',
    'bo': 'sa',
    'br': 'sa',
    'cl': 'sa',
    'co': 'sa',
    'ec': 'sa',
    'fk': 'sa',
    'gf': 'sa',
    'gy': 'sa',
    'pe': 'sa',
    'py': 'sa',
    'sr': 'sa',
    'uy': 'sa',
    've': 'sa',
    'as': 'oc',
    'ck': 'oc',
    'cx': 'oc',
    'fj': 'oc',
    'fm': 'oc',
    'gu': 'oc',
    'ki': 'oc',
    'mh': 'oc',
    'mp': 'oc',
    'nc': 'oc',
    'nf': 'oc',
    'nr': 'oc',
    'nu': 'oc',
    'nz': 'oc',
    'pf': 'oc',
    'pg': 'oc',
    'pn': 'oc',
    'pw': 'oc',
    'sb': 'oc',
    'tk': 'oc',
    'to': 'oc',
    'tv': 'oc',
    'um': 'oc',
    'vu': 'oc',
    'wf': 'oc',
    'ws': 'oc',
    'au': 'oc',
}

CONTINENTS: dict[str, dict] = {
    "as": {"order": 10, "label": "\U0001F30F Asia",          "bg": "#b9770e"},
    "eu": {"order": 20, "label": "\U0001F30D Europe",        "bg": "#1f3a93"},
    "na": {"order": 30, "label": "\U0001F30E North America", "bg": "#0b5d3b"},
    "sa": {"order": 40, "label": "\U0001F30E South America", "bg": "#1e8449"},
    "af": {"order": 50, "label": "\U0001F30D Africa",        "bg": "#7d6608"},
    "oc": {"order": 60, "label": "\U0001F30F Oceania",       "bg": "#0e6251"},
    "other": {"order": 90, "label": "\U0001F30D Others",     "bg": "#5d6d7e"},
}


def continent_of(code: str) -> str:
    return _CONTINENT_OF.get((code or "").strip().lower(), "other")


def continent_meta(key: str) -> dict:
    return CONTINENTS.get(key, CONTINENTS["other"])
